# Singularity Extractor


In [2]:
import numpy as np
import tensorflow as tf

seed = 173
np.random.seed(seed)

In [3]:
kernel_size = 5
strides = 2
padding = "CONSTANT"
input_mat = tf.constant([
    [ 1, 2, 3, 4, 5],
    [ 6, 7, 8, 9,10],
    [11,12, 1,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
degree = 6

input_shape = input_mat.shape
output = np.zeros(input_shape)
radius = int((kernel_size - 1)/2) * strides
matpad = tf.pad(input_mat, tf.constant([[radius, radius], [radius, radius]]), mode=padding)

for y in range(input_shape[1]):
    for x in range(input_shape[0]):
        _x, _y = x + radius, y + radius
        kernel = matpad[_y - radius:_y + 1 + radius:strides, _x - radius: _x + 1 + radius:strides]
        redsum = tf.reduce_sum(kernel)
        output[y, x] = ((redsum - input_mat[x, y]) / redsum) ** degree

print(input_mat)
print("-----------------------")
print((tf.round(output * 100)/100)[1:-1, 1:-1])

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  1 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]], shape=(5, 5), dtype=int32)
-----------------------
tf.Tensor(
[[0.42 0.37 0.09]
 [0.52 0.94 0.21]
 [0.32 0.31 0.07]], shape=(3, 3), dtype=float64)
