# Singularity Extractor - Non-optimized

In [2]:
import numpy as np
import tensorflow as tf

seed = 173
np.random.seed(seed)

In [3]:
kernel_size = 3
strides = 1
padding = "CONSTANT"
input_mat = tf.constant([
    [ 1, 2, 3, 4, 5],
    [ 6, 7, 8, 9,10],
    [11,12, 1,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
degree = 6
margin = 1

input_shape = input_mat.shape
output = np.zeros(input_shape)
radius = int((kernel_size - 1)/2) * strides
matpad = tf.pad(input_mat, tf.constant([[radius, radius], [radius, radius]]), mode=padding)

for y in range(input_shape[1]):
    for x in range(input_shape[0]):
        _x, _y = x + radius, y + radius
        kernel = matpad[_y - radius:_y + 1 + radius:strides, _x - radius: _x + 1 + radius:strides]
        redsum = tf.reduce_sum(kernel)
        output[y, x] = ((redsum - input_mat[x, y]) / redsum) ** degree

print(input_mat)
print("-----------------------")
print((tf.round(output * 100)/100)[margin:-margin, margin:-margin])

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  1 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]], shape=(5, 5), dtype=int32)
-----------------------
tf.Tensor(
[[0.41 0.26 0.18]
 [0.59 0.94 0.36]
 [0.67 0.56 0.47]], shape=(3, 3), dtype=float64)


# Optimized

In [4]:
xx = tf.pad(tf.stack([input_mat, input_mat, input_mat]), [[0, 0],[2, 2], [2, 2]])
xx = tf.reshape(xx, (3,9,9,1))
xx

<tf.Tensor: shape=(3, 9, 9, 1), dtype=int32, numpy=
array([[[[ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0]],

        [[ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0],
         [ 0]],

        [[ 0],
         [ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 0],
         [ 0]],

        [[ 0],
         [ 0],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [ 0],
         [ 0]],

        [[ 0],
         [ 0],
         [11],
         [12],
         [ 1],
         [14],
         [15],
         [ 0],
         [ 0]],

        [[ 0],
         [ 0],
         [16],
         [17],
         [18],
         [19],
         [20],
         [ 0],
         [ 0]],

        [[ 0],
         [ 0],
         [21],
         [22],
         [23],
         [24],
         [25],
         [ 0],
      

In [5]:
ones = tf.ones((3, 3, 1, 1), dtype="int32")
ones

<tf.Tensor: shape=(3, 3, 1, 1), dtype=int32, numpy=
array([[[[1]],

        [[1]],

        [[1]]],


       [[[1]],

        [[1]],

        [[1]]],


       [[[1]],

        [[1]],

        [[1]]]])>

In [6]:
(xx.shape, ones.shape)

(TensorShape([3, 9, 9, 1]), TensorShape([3, 3, 1, 1]))

In [7]:
tf.nn.convolution(xx, ones)

<tf.Tensor: shape=(3, 7, 7, 1), dtype=int32, numpy=
array([[[[  1],
         [  3],
         [  6],
         [  9],
         [ 12],
         [  9],
         [  5]],

        [[  7],
         [ 16],
         [ 27],
         [ 33],
         [ 39],
         [ 28],
         [ 15]],

        [[ 18],
         [ 39],
         [ 51],
         [ 60],
         [ 69],
         [ 57],
         [ 30]],

        [[ 33],
         [ 69],
         [ 96],
         [105],
         [114],
         [ 87],
         [ 45]],

        [[ 48],
         [ 99],
         [141],
         [150],
         [159],
         [117],
         [ 60]],

        [[ 37],
         [ 76],
         [117],
         [123],
         [129],
         [ 88],
         [ 45]],

        [[ 21],
         [ 43],
         [ 66],
         [ 69],
         [ 72],
         [ 49],
         [ 25]]],


       [[[  1],
         [  3],
         [  6],
         [  9],
         [ 12],
         [  9],
         [  5]],

        [[  7],
         [ 16],
  